# The Restaurant Gender & Smoking Independence Test (Chi-Square Test of Independence)

### Objective:
Analyze the `tips` dataset from Seaborn to investigate whether the gender (`sex`) and smoking habit (`smoker`) are statistically independent or dependent variables using the Chi-Square Test of Independence.

>Test Used: Chi-Square Test of Independence

>Performed by : Raghav Katyal on 01 October 2026

In [15]:
import pandas as pd
import seaborn as sns
from scipy import stats

In [16]:
df = sns.load_dataset('tips')

In [17]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#Creating the 2x2 contingency table crossing 'sex' and 'smoker' columns.
contingency_table = pd.crosstab(index=df['sex'],columns=df['smoker'])

In [24]:
display(contingency_table)

smoker  Yes  No
sex
Male     60  97
Female   33  54

In [ ]:
#Running the Chi-Square Test of Independence
chi_stat,p_value,_,_ = stats.chi2_contingency(contingency_table)

In [21]:
print(f"Chi-Square Score : {chi_stat:.2f}")
print(f"P-value : {p_value:.5f}")

Chi-Square Score : 0.00
P-value : 1.00000

>Observation : A Chi-Square score of 0.00 and p-value score of 1.00 shows absolutely no strong evidence against the independence of data ; data passes the independence test. Hence it is statistically observed that : Smoking Choice is independent and not bound to Sex/Gender.