# Quota Sampling Method in Python

> Mission : A developer wants real user reviews of his newly deployed app for enhancing it further. He needs reviews for especially how the app performs on different Operating Systems. Based on requirement he wants a sample of 3000 reviews distributed among : 60% Windows users, 25% Linux users and 15% MacOS users from the total user reviews base.

### Strategy :
1. Using Numpy to simulate a batch of 12000 reviews combining all 3 OS platforms.
2. Using Pandas, Merging "user_id" and "user_os" in one DataFrame (df)
3. Selecting 3000 users using quota sampling based on the ratio 60:25:15 as required for study.

### Sampling Method:
Non Representative Sampling : Quota Sampling Method

>Example created & performed in python by : Raghav Katyal on 29th September 2026

In [175]:
#importing required libraries
import numpy as np
import pandas as pd

In [176]:
#batch size (Creating the population/ universe of reviews)
batch = 12000
user_id = np.arange(1,batch+1)

user_os = ["windows","linux","mac"] * 4000
np.random.shuffle(user_os)

In [177]:
#merging into one Data Frame
df = pd.DataFrame({
    "user_id" : user_id,
    "user_os" : user_os
})

#requires sample for study is 3000 among 12000
sample_size = 3000

In [178]:
#selecting reviews from each OS in the 60:25:15 ratio required for study
windows_60 = df[df['user_os'] == "windows"].head(int((60/100)*3000))
linux_25 = df[df['user_os'] == "linux"].head(int((25/100)*3000))
mac_15 = df[df['user_os'] == "mac"].head(int((15/100)*3000))

In [179]:
#inspecting the correctness in each DataFrame
display(windows_60.head(5))
display(linux_25.head(5))
display(mac_15.head(5))

   user_id  user_os
0        1  windows
2        3  windows
5        6  windows
7        8  windows
9       10  windows

    user_id user_os
3         4   linux
4         5   linux
11       12   linux
14       15   linux
16       17   linux

    user_id user_os
1         2     mac
6         7     mac
8         9     mac
13       14     mac
17       18     mac

In [180]:
final_quota_sample = pd.concat([windows_60,linux_25,mac_15])

In [181]:
final_quota_sample.head(5)

   user_id  user_os
0        1  windows
2        3  windows
5        6  windows
7        8  windows
9       10  windows

In [182]:
len(final_quota_sample[final_quota_sample["user_os"] == "windows"])

1800

In [183]:
print(f"Total Reviews fetched : {len(final_quota_sample)}")
print(f"\nThe Ratio:")
display(final_quota_sample['user_os'].value_counts())

Total Reviews fetched : 3000

The Ratio:

user_os
windows    1800
linux       750
mac         450
Name: count, dtype: int64

In [184]:
print("Quota Sampling Successfull!")

Quota Sampling Successfull!