# Stratified Sampling Method in Python

> Mission : A developer wants real user reviews of his newly deployed app for enhancing it further. He needs reviews for especially how the app performs on different Operating Systems. Based on requirement he wants a random sample of 3000 reviews distributed among : 60% Windows users, 25% Linux users and 15% MacOS users from the total user reviews base.

### Strategy :
1. Using Numpy to simulate a batch of 12000 reviews combining all 3 OS platforms.
2. Using Pandas, Merging "user_id" and "user_os" in one DataFrame (df)
3. Selecting random 3000 users using stratified sampling based on the ratio 60:25:15 as required for study.

### Sampling Method:
Probability Sampling : Stratified Sampling Method

>Example created & performed in python by : Raghav Katyal on 29th September 2026

In [79]:
#importing required libraries
import numpy as np
import pandas as pd

In [80]:
#batch size (Creating the population/ universe of reviews)
batch = 12000
user_id = np.arange(1,batch+1)

user_os = ["windows","linux","mac"] * 4000
np.random.shuffle(user_os)

In [81]:
#merging into one Data Frame
df = pd.DataFrame({
    "user_id" : user_id,
    "user_os" : user_os
})

#requires sample for study is 3000 among 12000
sample_size = 3000

In [82]:
#selecting random reviews from each OS in the 60:25:15 ratio required for study
windows_60 = df[df['user_os']=="windows"].sample(int((60/100)*sample_size))
linux_25 = df[df['user_os']=="linux"].sample(int((25/100)*sample_size))
mac_15 = df[df['user_os']=="mac"].sample(int((15/100)*sample_size))

In [83]:
#inspecting the correctness in each DataFrame
display(windows_60.head(5))
display(linux_25.head(5))
display(mac_15.head(5))

       user_id  user_os
1417      1418  windows
11524    11525  windows
8976      8977  windows
1867      1868  windows
3597      3598  windows

      user_id user_os
3544     3545   linux
3469     3470   linux
8039     8040   linux
7364     7365   linux
1831     1832   linux

      user_id user_os
6824     6825     mac
6643     6644     mac
556       557     mac
1614     1615     mac
9086     9087     mac

In [84]:
final_stratified_sample = pd.concat([windows_60,linux_25,mac_15])

In [85]:
print(f"Total Reviews fetched : {len(final_stratified_sample)}")
print(f"\nThe Ratio:")
display(final_stratified_sample['user_os'].value_counts())

Total Reviews fetched : 3000

The Ratio:

user_os
windows    1800
linux       750
mac         450
Name: count, dtype: int64

In [86]:
print("Stratified Sampling Successfull!")

Stratified Sampling Successfull!